import os
from dotenv import load_dotenv


# ENVIRONMENT VARIABLES
load_dotenv()

### DATABASE
DB_URL = str(os.getenv("DB_URL"))

### EPC API
EPC_API_CREDENTIALS = str(os.getenv("UK_EPC_API_AUTHENTICATION_TOKEN"))


# RUNTIME CONFIGURATIONS

## EPC data is available from this year and month
EPC_MIN_YEAR = 2008
EPC_MIN_MONTH = 10

COLUMN_TYPES = {"residential_energy_performance_certificate": {"lmk_key": "string",
                                                        "address1": "string",
                                                        "address2": "string",
                                                        "address3": "string",
                                                        "postcode": "string",
                                                        "building_reference_number": "string",
                                                        "current_energy_rating": "string",
                                                        "potential_energy_rating": "string",
                                                        "current_energy_efficiency": float,
                                                        "potential_energy_efficiency": float,
                                                        "property_type": "string",
                                                        "built_form": "string",
                                                        "inspection_date": "datetime64[ns]",
                                                        "local_authority": "string",
                                                        "constituency": "string",
                                                        "county": "string",
                                                        "lodgement_date": "datetime64[ns]",
                                                        "transaction_type": "string",
                                                        "environment_impact_current": float,
                                                        "environment_impact_potential": float,
                                                        "energy_consumption_current": float,
                                                        "energy_consumption_potential": float,
                                                        "co2_emissions_current": float,
                                                        "co2_emiss_curr_per_floor_area": float,
                                                        "co2_emissions_potential": float,
                                                        "lighting_cost_current": float,
                                                        "lighting_cost_potential": float,
                                                        "heating_cost_current": float,
                                                        "heating_cost_potential": float,
                                                        "hot_water_cost_current": float,
                                                        "hot_water_cost_potential": float,
                                                        "total_floor_area": float,
                                                        "energy_tariff": "string",
                                                        "mains_gas_flag": "string",
                                                        "floor_level": "string",
                                                        "flat_top_storey": "string",
                                                        "flat_storey_count": float,
                                                        "main_heating_controls": float,
                                                        "multi_glaze_proportion": float,
                                                        "glazed_type": "string",
                                                        "glazed_area": "string",
                                                        "extension_count": float,
                                                        "number_habitable_rooms": float,
                                                        "number_heated_rooms": float,
                                                        "low_energy_lighting": float,
                                                        "number_open_fireplaces": float,
                                                        "hotwater_description": "string",
                                                        "hot_water_energy_eff": "string",
                                                        "hot_water_env_eff": "string",
                                                        "floor_description": "string",
                                                        "floor_energy_eff": "string",
                                                        "floor_env_eff": "string",
                                                        "windows_description": "string",
                                                        "windows_energy_eff": "string",
                                                        "windows_env_eff": "string",
                                                        "walls_description": "string",
                                                        "walls_energy_eff": "string",
                                                        "walls_env_eff": "string",
                                                        "secondheat_description": "string",
                                                        "sheating_energy_eff": "string",
                                                        "sheating_env_eff": "string",
                                                        "roof_description": "string",
                                                        "roof_energy_eff": "string",
                                                        "roof_env_eff": "string",
                                                        "mainheat_description": "string",
                                                        "mainheat_energy_eff": "string",
                                                        "mainheat_env_eff": "string",
                                                        "mainheatcont_description": "string",
                                                        "mainheatc_energy_eff": "string",
                                                        "mainheatc_env_eff": "string",
                                                        "lighting_description": "string",
                                                        "lighting_energy_eff": "string",
                                                        "lighting_env_eff": "string",
                                                        "main_fuel": "string",
                                                        "wind_turbine_count": float,
                                                        "heat_loss_corridor": "string",
                                                        "unheated_corridor_length": float,
                                                        "floor_height": float,
                                                        "photo_supply": float,
                                                        "solar_water_heating_flag": "string",
                                                        "mechanical_ventilation": "string",
                                                        "address": "string",
                                                        "local_authority_label": "string",
                                                        "constituency_label": "string",
                                                        "posttown": "string",
                                                        "construction_age_band": "string",
                                                        "lodgement_datetime": "datetime64[ns]",
                                                        "tenure": "string",
                                                        "fixed_lighting_outlets_count": float,
                                                        "low_energy_fixed_light_count": float,
                                                        "uprn": "string",
                                                        "uprn_source": "string"
                                                        }
                }

EPC_LOCAL_AUTHORITIES = {"Adur": "E07000223",
                         "Allerdale": "E07000026",
                         "Amber Valley": "E07000032",
                         "Arun": "E07000224",
                         "Ashfield": "E07000170",
                         "Ashford": "E07000105",
                         "Aylesbury Vale": "E07000004",
                         "Babergh": "E07000200",
                         "Barking and Dagenham": "E09000002",
                         "Barnet": "E09000003",
                         "Barnsley": "E08000016",
                         "Barrow-in-Furness": "E07000027",
                         "Basildon": "E07000066",
                         "Basingstoke and Deane": "E07000084",
                         "Bassetlaw": "E07000171",
                         "Bath and North East Somerset": "E06000022",
                         "Bedford": "E06000055",
                         "Bexley": "E09000004",
                         "Birmingham": "E08000025",
                         "Blaby": "E07000129",
                         "Blackburn with Darwen": "E06000008",
                         "Blackpool": "E06000009",
                         "Blaenau Gwent": "W06000019",
                         "Bolsover": "E07000033",
                         "Bolton": "E08000001",
                         "Boston": "E07000136",
                         "Bournemouth, Christchurch and Poole": "E06000058",
                         "Bracknell Forest": "E06000036",
                         "Bradford": "E08000032",
                         "Braintree": "E07000067",
                         "Breckland": "E07000143",
                         "Brent": "E09000005",
                         "Brentwood": "E07000068",
                         "Bridgend": "W06000013",
                         "Brighton and Hove": "E06000043",
                         "Bristol, City of": "E06000023",
                         "Broadland": "E07000144",
                         "Bromley": "E09000006",
                         "Bromsgrove": "E07000234",
                         "Broxbourne": "E07000095",
                         "Broxtowe": "E07000172",
                         "Buckinghamshire": "E06000060",
                         "Burnley": "E07000117",
                         "Bury": "E08000002",
                         "Caerphilly": "W06000018",
                         "Calderdale": "E08000033",
                         "Cambridge": "E07000008",
                         "Camden": "E09000007",
                         "Cannock Chase": "E07000192",
                         "Canterbury": "E07000106",
                         "Cardiff": "W06000015",
                         "Carlisle": "E07000028",
                         "Carmarthenshire": "W06000010",
                         "Castle Point": "E07000069",
                         "Central Bedfordshire": "E06000056",
                         "Ceredigion": "W06000008",
                         "Charnwood": "E07000130",
                         "Chelmsford": "E07000070",
                         "Cheltenham": "E07000078",
                         "Cherwell": "E07000177",
                         "Cheshire East": "E06000049",
                         "Cheshire West and Chester": "E06000050",
                         "Chesterfield": "E07000034",
                         "Chichester": "E07000225",
                         "Chiltern": "E07000005",
                         "Chorley": "E07000118",
                         "City of London": "E09000001",
                         "Colchester": "E07000071",
                         "Conwy": "W06000003",
                         "Copeland": "E07000029",
                         "Corby": "E07000150",
                         "Cornwall": "E06000052",
                         "Cotswold": "E07000079",
                         "County Durham": "E06000047",
                         "Coventry": "E08000026",
                         "Craven": "E07000163",
                         "Crawley": "E07000226",
                         "Croydon": "E09000008",
                         "Dacorum": "E07000096",
                         "Darlington": "E06000005",
                         "Dartford": "E07000107",
                         "Daventry": "E07000151",
                         "Denbighshire": "W06000004",
                         "Derby": "E06000015",
                         "Derbyshire Dales": "E07000035",
                         "Doncaster": "E08000017",
                         "Dorset": "E06000059",
                         "Dover": "E07000108",
                         "Dudley": "E08000027",
                         "Ealing": "E09000009",
                         "East Cambridgeshire": "E07000009",
                         "East Devon": "E07000040",
                         "East Hampshire": "E07000085",
                         "East Hertfordshire": "E07000242",
                         "East Lindsey": "E07000137",
                         "East Northamptonshire": "E07000152",
                         "East Riding of Yorkshire": "E06000011",
                         "East Staffordshire": "E07000193",
                         "East Suffolk": "E07000244",
                         "Eastbourne": "E07000061",
                         "Eastleigh": "E07000086",
                         "Eden": "E07000030",
                         "Elmbridge": "E07000207",
                         "Enfield": "E09000010",
                         "Epping Forest": "E07000072",
                         "Epsom and Ewell": "E07000208",
                         "Erewash": "E07000036",
                         "Exeter": "E07000041",
                         "Fareham": "E07000087",
                         "Fenland": "E07000010",
                         "Flintshire": "W06000005",
                         "Folkestone and Hythe": "E07000112",
                         "Forest of Dean": "E07000080",
                         "Fylde": "E07000119",
                         "Gateshead": "E08000037",
                         "Gedling": "E07000173",
                         "Gloucester": "E07000081",
                         "Gosport": "E07000088",
                         "Gravesham": "E07000109",
                         "Great Yarmouth": "E07000145",
                         "Greenwich": "E09000011",
                         "Guildford": "E07000209",
                         "Gwynedd": "W06000002",
                         "Hackney": "E09000012",
                         "Halton": "E06000006",
                         "Hambleton": "E07000164",
                         "Hammersmith and Fulham": "E09000013",
                         "Harborough": "E07000131",
                         "Haringey": "E09000014",
                         "Harlow": "E07000073",
                         "Harrogate": "E07000165",
                         "Harrow": "E09000015",
                         "Hart": "E07000089",
                         "Hartlepool": "E06000001",
                         "Hastings": "E07000062",
                         "Havant": "E07000090",
                         "Havering": "E09000016",
                         "Herefordshire, County of": "E06000019",
                         "Hertsmere": "E07000098",
                         "High Peak": "E07000037",
                         "Hillingdon": "E09000017",
                         "Hinckley and Bosworth": "E07000132",
                         "Horsham": "E07000227",
                         "Hounslow": "E09000018",
                         "Huntingdonshire": "E07000011",
                         "Hyndburn": "E07000120",
                         "Ipswich": "E07000202",
                         "Isle of Anglesey": "W06000001",
                         "Isle of Wight": "E06000046",
                         "Isles of Scilly": "E06000053",
                         "Islington": "E09000019",
                         "Kensington and Chelsea": "E09000020",
                         "Kettering": "E07000153",
                         "King's Lynn and West Norfolk": "E07000146",
                         "Kingston upon Hull, City of": "E06000010",
                         "Kingston upon Thames": "E09000021",
                         "Kirklees": "E08000034",
                         "Knowsley": "E08000011",
                         "Lambeth": "E09000022",
                         "Lancaster": "E07000121",
                         "Leeds": "E08000035",
                         "Leicester": "E06000016",
                         "Lewes": "E07000063",
                         "Lewisham": "E09000023",
                         "Lichfield": "E07000194",
                         "Lincoln": "E07000138",
                         "Liverpool": "E08000012",
                         "Luton": "E06000032",
                         "Maidstone": "E07000110",
                         "Maldon": "E07000074",
                         "Malvern Hills": "E07000235",
                         "Manchester": "E08000003",
                         "Mansfield": "E07000174",
                         "Medway": "E06000035",
                         "Melton": "E07000133",
                         "Mendip": "E07000187",
                         "Merthyr Tydfil": "W06000024",
                         "Merton": "E09000024",
                         "Mid Devon": "E07000042",
                         "Mid Suffolk": "E07000203",
                         "Mid Sussex": "E07000228",
                         "Middlesbrough": "E06000002",
                         "Milton Keynes": "E06000042",
                         "Mole Valley": "E07000210",
                         "Monmouthshire": "W06000021",
                         "Neath Port Talbot": "W06000012",
                         "New Forest": "E07000091",
                         "Newark and Sherwood": "E07000175",
                         "Newcastle upon Tyne": "E08000021",
                         "Newcastle-under-Lyme": "E07000195",
                         "Newham": "E09000025",
                         "Newport": "W06000022",
                         "North Devon": "E07000043",
                         "North East Derbyshire": "E07000038",
                         "North East Lincolnshire": "E06000012",
                         "North Hertfordshire": "E07000099",
                         "North Kesteven": "E07000139",
                         "North Lincolnshire": "E06000013",
                         "North Norfolk": "E07000147",
                         "North Northamptonshire": "E06000061",
                         "North Somerset": "E06000024",
                         "North Tyneside": "E08000022",
                         "North Warwickshire": "E07000218",
                         "North West Leicestershire": "E07000134",
                         "Northampton": "E07000154",
                         "Northumberland": "E06000057",
                         "Norwich": "E07000148",
                         "Nottingham": "E06000018",
                         "Nuneaton and Bedworth": "E07000219",
                         "Oadby and Wigston": "E07000135",
                         "Oldham": "E08000004",
                         "Oxford": "E07000178",
                         "Pembrokeshire": "W06000009",
                         "Pendle": "E07000122",
                         "Peterborough": "E06000031",
                         "Plymouth": "E06000026",
                         "Portsmouth": "E06000044",
                         "Powys": "W06000023",
                         "Preston": "E07000123",
                         "Reading": "E06000038",
                         "Redbridge": "E09000026",
                         "Redcar and Cleveland": "E06000003",
                         "Redditch": "E07000236",
                         "Reigate and Banstead": "E07000211",
                         "Rhondda Cynon Taf": "W06000016",
                         "Ribble Valley": "E07000124",
                         "Richmond upon Thames": "E09000027",
                         "Richmondshire": "E07000166",
                         "Rochdale": "E08000005",
                         "Rochford": "E07000075",
                         "Rossendale": "E07000125",
                         "Rother": "E07000064",
                         "Rotherham": "E08000018",
                         "Rugby": "E07000220",
                         "Runnymede": "E07000212",
                         "Rushcliffe": "E07000176",
                         "Rushmoor": "E07000092",
                         "Rutland": "E06000017",
                         "Ryedale": "E07000167",
                         "Salford": "E08000006",
                         "Sandwell": "E08000028",
                         "Scarborough": "E07000168",
                         "Sedgemoor": "E07000188",
                         "Sefton": "E08000014",
                         "Selby": "E07000169",
                         "Sevenoaks": "E07000111",
                         "Sheffield": "E08000019",
                         "Shropshire": "E06000051",
                         "Slough": "E06000039",
                         "Solihull": "E08000029",
                         "Somerset West and Taunton": "E07000246",
                         "South Bucks": "E07000006",
                         "South Cambridgeshire": "E07000012",
                         "South Derbyshire": "E07000039",
                         "South Gloucestershire": "E06000025",
                         "South Hams": "E07000044",
                         "South Holland": "E07000140",
                         "South Kesteven": "E07000141",
                         "South Lakeland": "E07000031",
                         "South Norfolk": "E07000149",
                         "South Northamptonshire": "E07000155",
                         "South Oxfordshire": "E07000179",
                         "South Ribble": "E07000126",
                         "South Somerset": "E07000189",
                         "South Staffordshire": "E07000196",
                         "South Tyneside": "E08000023",
                         "Southampton": "E06000045",
                         "Southend-on-Sea": "E06000033",
                         "Southwark": "E09000028",
                         "Spelthorne": "E07000213",
                         "St Albans": "E07000240",
                         "St. Helens": "E08000013",
                         "Stafford": "E07000197",
                         "Staffordshire Moorlands": "E07000198",
                         "Stevenage": "E07000243",
                         "Stockport": "E08000007",
                         "Stockton-on-Tees": "E06000004",
                         "Stoke-on-Trent": "E06000021",
                         "Stratford-on-Avon": "E07000221",
                         "Stroud": "E07000082",
                         "Sunderland": "E08000024",
                         "Surrey Heath": "E07000214",
                         "Sutton": "E09000029",
                         "Swale": "E07000113",
                         "Swansea": "W06000011",
                         "Swindon": "E06000030",
                         "Tameside": "E08000008",
                         "Tamworth": "E07000199",
                         "Tandridge": "E07000215",
                         "Teignbridge": "E07000045",
                         "Telford and Wrekin": "E06000020",
                         "Tendring": "E07000076",
                         "Test Valley": "E07000093",
                         "Tewkesbury": "E07000083",
                         "Thanet": "E07000114",
                         "Three Rivers": "E07000102",
                         "Thurrock": "E06000034",
                         "Tonbridge and Malling": "E07000115",
                         "Torbay": "E06000027",
                         "Torfaen": "W06000020",
                         "Torridge": "E07000046",
                         "Tower Hamlets": "E09000030",
                         "Trafford": "E08000009",
                         "Tunbridge Wells": "E07000116",
                         "Uttlesford": "E07000077",
                         "Vale of Glamorgan": "W06000014",
                         "Vale of White Horse": "E07000180",
                         "Wakefield": "E08000036",
                         "Walsall": "E08000030",
                         "Waltham Forest": "E09000031",
                         "Wandsworth": "E09000032",
                         "Warrington": "E06000007",
                         "Warwick": "E07000222",
                         "Watford": "E07000103",
                         "Waverley": "E07000216",
                         "Wealden": "E07000065",
                         "Wellingborough": "E07000156",
                         "Welwyn Hatfield": "E07000241",
                         "West Berkshire": "E06000037",
                         "West Devon": "E07000047",
                         "West Lancashire": "E07000127",
                         "West Lindsey": "E07000142",
                         "West Northamptonshire": "E06000062",
                         "West Oxfordshire": "E07000181",
                         "West Suffolk": "E07000245",
                         "Westminster": "E09000033",
                         "Wigan": "E08000010",
                         "Wiltshire": "E06000054",
                         "Winchester": "E07000094",
                         "Windsor and Maidenhead": "E06000040",
                         "Wirral": "E08000015",
                         "Woking": "E07000217",
                         "Wokingham": "E06000041",
                         "Wolverhampton": "E08000031",
                         "Worcester": "E07000237",
                         "Worthing": "E07000229",
                         "Wrexham": "W06000006",
                         "Wychavon": "E07000238",
                         "Wycombe": "E07000007",
                         "Wyre": "E07000128",
                         "Wyre Forest": "E07000239",
                         "York": "E06000014"
                        }

NAN_PATTERNS = ["N/A", "NaN", "nan", "unknown", "UNKNOWN", "Unknown", "INVALID!", "NODATA!", "NO DATA!", ""]
REDUNDANT_PATTERNS = ["%%MAINHEATCONTROL%%"]
FLOOR_LEVEL_PATTERNS = {r'^ground floor$': 'ground',
                        r'^mid floor$': 'mid',
                        r'^top floor$': 'top',
                        r'^\-1$': 'basement',
                        r'^0$': 'ground',
                        r'^00$': 'ground',
                        r'^1$': '1st',
                        r'^01$': '1st',
                        r'^2$': '2nd',
                        r'^02$': '2nd',
                        r'^3$': '3rd',
                        r'^03$': '3rd',
                        r'^4$': '4th',
                        r'^04$': '4th',
                        r'^5$': '5th',
                        r'^05$': '5th',
                        r'^6$': '6th',
                        r'^06$': '6th',
                        r'^7$': '7th',
                        r'^07$': '7th',
                        r'^8$': '8th',
                        r'^08$': '8th',
                        r'^9$': '9th',
                        r'^09$': '9th',
                        r'^10$': '10th',
                        r'^11$': '11th',
                        r'^12$': '12th',
                        r'^13$': '13th',
                        r'^14$': '14th',
                        r'^15$': '15th',
                        r'^16$': '16th',
                        r'^17$': '17th',
                        r'^18$': '18th',
                        r'^19$': '19th',
                        r'^20$': '20th',
                        r'^20\+$': '21st or above'
                        }

# OUTPUT_DATA -> platform -> output_table_name -> bucket, country, subject, source, table_name, path_date_params, file_extension, column_types
OUTPUT_DATA =  {"DB": {"residential_energy_performance_certificate": {"table_name": "residential_energy_performance_certificate",
                                                            "db_schema": "linked_ppd_epc",
                                                            "column_types": COLUMN_TYPES["residential_energy_performance_certificate"]
                                                            }
                      }
                }

# INPUT_DATA -> platform -> output_table_name -> platform-specific configs
INPUT_DATA =  {"SOURCE": {"residential_energy_performance_certificate":  {"endpoint_url": "https://epc.opendatacommunities.org/api/v1/domestic/search?",
                                                                  "endpoint_headers": {"Accept": "application/json", "Authorization": EPC_API_CREDENTIALS},
                                                                  "api_max_read_size": 5000,
                                                                  "api_max_read_total": 10000
                                                                  }
                           }
               }